import { Montserrat, Orbitron } from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber";

const montserrat = Montserrat({
  variable: "--font-Montserrat-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
});
const orbitron = Orbitron({
  variable: "--font-Orbitron-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
});


export const metadata = {
  title: "Cyber Ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${orbitron.variable} antialiased`}
      >
         <Navber/>
        {children}
      </body>
    </html>
  );
}
